### ISSUE TITLE
SNATing for pod IP space to be done only when leaving a private network

### ISSUE THREAD

**Issue by k10a** [aws/amazon-vpc-cni-k8s#44]
Pods in a VPC can talk to:
1. Internet
2. Pods or Instances in another VPC that is connected with a VPC peering connection.
3. Instances or pods in other AWS accounts, but the VPCs involved are part of the same network space and are reachable to each other eg: using architecture like transit-vpc 
4. Resources on prem directly reachable using a private IP space using aws components like Direct Connect Gateway.

SNATing should not be done in cases 2-4.
What IP space should involve NATing should be configurable instead of defaulting to VPC CIDR
https://github.com/aws/amazon-vpc-cni-k8s/blob/eb8fc860485934f0104a976a8e20a2159b745edb/pkg/networkutils/network.go#L99

**Comment by incognick** [comment]
Is this being addressed?  Currently in the EKS preview I cannot access Pods through a VPC peering connection that are assigned secondary IPs.

**Comment by liwenwu-amazon** [comment]
this should be addressed by PR #81

**Comment by incognick** [comment]
@liwenwu-amazon This is still an issue. I have updated to the latest CNI
